defaults:
  - _self_
  - config: MultiGoal-v0
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

hydra:  
  output_subdir: null  
  run:  
    dir: .

# Basic setups
project: SQL
env: MultiGoal-v0
description: standard
algo: sql
seed: 0
deterministic: !!bool False

# Hyper-parameters
buffer_size: 1000000
warmup_steps: 5000
eval_every: 1000
steps: 1000000
batch_size: 256
test_num: 10
wandb: 0
device: cuda

# (Actor Critic) ----
actor_lr: !!float 3e-4
critic_lr: !!float 3e-4
hidden_sizes: 128
hidden_layers: 2
n_particles: 16
gamma: 0.99
tau: 0.005
reward_scale: 0.1